name: Erlang CI

on:
  push:
    branches: main
    tags: '*'
  pull_request:
    branches: '*'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: erlang:23.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Compile
        run: rebar3 compile

      - name: Run EUnit tests
        run: rebar3 eunit

      - name: Run CT tests
        run: rebar3 ct

      - name: Check formatting
        run: rebar3 fmt --check
